#!/bin/php
<?php

    require('./tools/tools-lib.php');

	define('PROJECT_NAME', 'Emeraude-Engine');
	define('PROJECT_PLACE', 'https://github.com/londnoir/emeraude-engine');
	define('IDENTITY', 'Sébastien Léon Claude Christian Bémelmans "LondNoir" <londnoir@gmail.com>');

	$paths = [
		'./src'
	];

	$extensions = [
		'h', 'hpp',
		'c', 'cpp',
		'in'
	];

	$exclusions = [
		'txt'
	];

	/* =========== Execution =========== */

	$fileCount = 0;

	foreach ( $paths as $path )
	{
		$fileCount += crawl_directory($path, $extensions, $exclusions, 'lgpl3');
	}

	echo 
		$fileCount . ' files processed.' . PHP_EOL . 
		'Code statistics : ' . PHP_EOL;

	system('sloccount ' . implode(' ', $paths));
