#!/bin/bash

set -e

if [ "${1}" = "-clang" ]; then
	export CC=/usr/bin/clang
	export CXX=/usr/bin/clang++

	COMPILER="Clang"
else
	export CC=/usr/bin/gcc
	export CXX=/usr/bin/g++

	COMPILER="GCC"
fi

BUILD_TYPE=Release
BUILD_DIR="/var/tmp/EmeraudeInstall/${COMPILER}/${BUILD_TYPE}"

echo "Installing Emeraude (${BUILD_TYPE}) using ${COMPILER} from temp directory '${BUILD_DIR}' ..."

echo "Configuring the cmake build directory '${BUILD_DIR}' ..."
cmake -S . -B ${BUILD_DIR} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUSE_SYSTEM_LIBRARIES=Off -DENABLE_SHARED_LIBRARY=On -DINSTALL_DEV=On -G Ninja
echo "======= DONE ======"

echo "Compiling (${COMPILER}) ..."
cmake --build ${BUILD_DIR} --config ${BUILD_TYPE}
echo "======= DONE ======"

echo "Installing ..."
sudo cmake --install ${BUILD_DIR}
echo "======= DONE ======"
