#!/bin/bash

set -e

echo "Installing build dependencies ..."

sudo apt update
sudo apt install g++ cmake ninja-build \
    glslang-dev glslang-tools libvulkan-dev vulkan-validationlayers-dev libglfw3-dev \
    libopenal-dev libalut-dev zlib1g-dev libpng-dev libjsoncpp-dev libjpeg-dev libfreetype-dev \
    libsndfile1-dev libsamplerate0-dev libtag1-dev libimgui-dev libasio-dev xorg-dev libaubio-dev

echo "Done !"
