#!/bin/bash

set -e

changed=0

git remote update && git status --porcelain -uno | grep -q 'Your branch is behind' && changed=1

if [ $changed = 1 ]; then
	echo "Rebasing local branch ...";

    git pull --rebase

    echo "Updated successfully !";
else
    echo "Up-to-date !"
fi

if [[ `git status --porcelain` ]]; then
	echo "Check your local changes before updating sub-modules !"
else
	git submodule update --recursive --remote

	git add --all
	git commit -m"Sub-modules updated"
	git push
fi
